### PR TITLE
Feature/8173 theo skeleton loader health screen

### PR DESCRIPTION
**Pull request by theodur**
## Description of Change

Adds skeleton loading to the `LargeNavButton` component, and updates home screen to include count logic.

## Screenshots/Video

Light mode: 

&nbsp;&nbsp;

Dark mode: 

&nbsp;&nbsp;image

## Testing

- [ ] Tested on iOS 
- [ ] Tested on Android 

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [ ] PR is connected to issue(s)
- [ ] Tests are included to cover this change (when possible)
- [ ] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [ ] No secrets or API keys are checked in
- [ ] All imports are absolute (no relative imports)
- [ ] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

### CODE REVIEW

**Review by dumathane — APPROVED** [review]

**Review by dumathane — CHANGES_REQUESTED** [review]
found issue with dark mode.

**Review by dumathane — APPROVED** [review]

**Comment by TKDickson** [comment]
Empty state for health activity doesn't match design (see more detailed comment in ticket 7478)

**Comment by TKDickson** [comment]
Annnnnd the skeleton loader for Android is announcing separately from the rest of the button (iOS is fine), see ticket 8173.

**Review by TKDickson — APPROVED** [review]
QA and VQA signoff to merge to XL

**Pull request merged**
