### PR TITLE
Documentation/6324-Chika-added-doc-for-be-detox

### PR DESCRIPTION
**Pull request by cadibemma**
## Description of Change

- This adds documentation on how to setup and start testing when BE Flex is needed
- department-of-veterans-affairs/va-mobile-app#6324

## Testing
- None (documentation)

## Reviewer Validations
- BE and QA approval of doc update

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [ ] PR is connected to issue(s)
- [ ] Tests are included to cover this change (when possible)
- [ ] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [ ] No secrets or API keys are checked in
- [ ] All imports are absolute (no relative imports)
- [ ] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

### CODE REVIEW

**Review by kpethtel — COMMENTED** [review]
The documentation itself looks good as far as I know, but it doesn't feel like it should be in the back end section of the wiki. Should this be in QA or front end instead? Are back end engineers expected to run these tests?

**Comment by cadibemma** [comment]
@kpethtel QA does have some documentation of how to setup detox but I didn't think it was enough for someone from BE with no other prior setup for testing. BE engineers will only need to run/write cases when we have space to flex and help QA out within a sprint.

**Comment by aherzberg** [comment]
I agree we should build upon the existing documentation (https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/Automation#detox-our-ui-automation-tool) already in QA section and if anything, include a link to that documentation in the Backend docs for reference.

**Review by kpethtel — APPROVED** [review]
LGTM. Thanks for moving it. Hopefully this makes the QA docs more useful to them too.

**Review by aherzberg — APPROVED** [review]
LGTM

**Pull request merged**
