### PR TITLE
8858/feature-theo-HomeScreenHSPRefactor

### PR DESCRIPTION
**Pull request by theodur**
## Description of Change

Refactors home screen code to make it more readible.

## Screenshots/Video

N/A

## Testing

- [ ] Tested on iOS 
- [ ] Tested on Android 

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [ ] PR is connected to issue(s)
- [ ] Tests are included to cover this change (when possible)
- [ ] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [ ] No secrets or API keys are checked in
- [ ] All imports are absolute (no relative imports)
- [ ] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

### CODE REVIEW

**Review by dumathane — APPROVED** [review]

**Comment by TKDickson** [comment]
@theodur can you rebase this off of develop? Mind you, no rush, I'm not planning on looking at it until next sprint at the earliest (and I will go add that to the ticket as well)

**Review by dumathane — APPROVED** [review]

**Comment by TKDickson** [comment]
@theodur can you resolve the merge conflict please? Not super urgent

**Comment by theodur** [comment]
@TKDickson Should be good now

**Review by TKDickson — APPROVED** [review]
Approved to merge to develop

**Pull request merged**
