### PR TITLE
Cu/3198-LizTownsend-use-click-to-call-component

### PR DESCRIPTION
**Pull request by liztownd**
## Description of Change
ClickToCallPhoneNumber is a pre-existing component that has been supplied to all locations we are providing a phone link. 

## Screenshots/Video
If there was an alternate TTY number provided, the phone number component uses the "ttybypass" prop to disable the separate "711" TTY display:

Veterans Crisis Line Before/after: 
&nbsp;&nbsp;

If there was not a separate TTY phone number, the "ttybypass" prop is not passed and the appropriate TTY number is shown:

Incorrect Military information Before/after: 
&nbsp;&nbsp;

## Testing
- [x] Tested on iOS 
- [x] Tested on Android 

## Reviewer Validations
This should replace all uses of the ClickForActionLink component where the linkType was LinkTypeOptionsConstants.call

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [ ] PR is connected to issue(s)
- [ ] Tests are included to cover this change (when possible)
- [ ] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [ ] No secrets or API keys are checked in
- [ ] All imports are absolute (no relative imports)
- [ ] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

### CODE REVIEW

**Review by Sparowhawk — CHANGES_REQUESTED** [review]
I had a separate ticket that got merged this morning that covered the incorrect service Info and I believe all of the MilitaryInfo e2e tests. Please fix the merge conflicts that may have caused.

**Comment by liztownd** [comment]
@Sparowhawk Done. (I did not see any merge conflicts or changes in the MilitaryInformation.e2e test file though.)

**Comment by Sparowhawk** [comment]
> @Sparowhawk Done. (I did not see any merge conflicts or changes in the MilitaryInformation.e2e test file though.)

from what I can tell the e2e file wasn't updated aside from spacing. could you revert those changes as the spacing shouldn't be adjusted

**Comment by liztownd** [comment]
@Sparowhawk I did make changes to that file, actually. I'm not sure why but it's not picking up the prettierrc settings in the e2e directory so that file it defaulting to tabs... 🤔 Let me see what I can do to make it work.

**Pull request closed without merging**
