### PR TITLE
Update Mobile App Org Chart to reflect new structure 

### PR DESCRIPTION
**Pull request by bischoffa**
## Description of Change

Update Mobile App Org Chart to reflect new structure 

## Testing

- [ ] Tested on iOS 
- [ ] Tested on Android 

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [ ] PR is connected to issue(s)
- [ ] Tests are included to cover this change (when possible)
- [ ] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [ ] No secrets or API keys are checked in
- [ ] All imports are absolute (no relative imports)
- [ ] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

### CODE REVIEW

**Comment by bischoffa** [comment]
@TimRoe here is the updated org chart with Victor on it and not Greta. Can we upload this up using this PR ? Or do I need to create another one?

**Comment by TimRoe** [comment]
I think Adam meant @timwright12 ?

Also, at a glance that image you linked looks like it's in `private-user-images` so I don't think it'd be visible to the public which I assume it should be.

**Comment by bischoffa** [comment]
Apologies meant @timwright12   
  
The original image Seth shared. I downloaded it and edited it to add Victor. Not sure if that is what its private user

**Comment by timwright12** [comment]
@bischoffa you can close this out, I just updated it right on the branch

**Pull request closed without merging**
