### PR TITLE
Automation/6261-chanel-bug-qa-approval-pr

### PR DESCRIPTION
**Pull request by IsraelleHub**
## Description of Change
Fix bug related to dependabot failing on pr
Fix bug relate to PR failing when qa and engineer approve PR
Verified updated workflow is running as expected on[https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/9865401195/job/27242268543](url)

## Screenshots/Video

screenshot_2024-07-09_at_4 04 13___pm

## Testing

- [ ] Tested on iOS 
- [ ] Tested on Android 

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [ ] PR is connected to issue(s)
- [ ] Tests are included to cover this change (when possible)
- [ ] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [ ] No secrets or API keys are checked in
- [ ] All imports are absolute (no relative imports)
- [ ] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

### CODE REVIEW

**Review by theodur — APPROVED** [review]

**Review by rbontrager — DISMISSED** [review]

**Review by IsraelleHub — COMMENTED** [review]
test1

**Review by IsraelleHub — COMMENTED** [review]
test

**Review by IsraelleHub — COMMENTED** [review]
test2

**Review by IsraelleHub — COMMENTED** [review]
test1

**Review by rbontrager — APPROVED** [review]

**Review by rbontrager — APPROVED** [review]

**Review by theodur — APPROVED** [review]

**Review by narin — APPROVED** [review]

**Review by timwright12 — APPROVED** [review]

**Pull request merged**
