### PR TITLE
Updated build tools version to 33

### PR DESCRIPTION
**Pull request by timwright12**
We got a warning that our target API level in Android needed to be updated to 33: https://play.google.com/console/u/0/developers/7507611851470273082/app/4974294731909201030/policy-center/issues/4988276614632641488/details

The deadline for this is Aug 30, 2023 or we won't be able to release to the play store.

**Violation**
App must target Android 13 (API level 33) or higher

> To provide users with a safe and secure experience, Google Play requires all apps to meet target API level requirements.
From Aug 30, 2023, if your target API level is not within 1 year of the latest Android release, you won't be able to update your app.

Research from here: https://onkarjanwa.com/how-to-update-android-target-api-level-in-react-native/

Verified working in emulator

Screenshot 2023-08-21 at 11 14 04 AM

### CODE REVIEW

**Comment by timwright12** [comment]
On demand build run: https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/5905024046

**Comment by alexandec** [comment]
- Built the app in Android studio with this branch and it ran fine in the emulator
- Built the app by running `yarn android` and it also ran fine

Not seeing any issues with local builds 👍

**Review by alexandec — APPROVED** [review]

**Review by narin — APPROVED** [review]

**Review by theodur — COMMENTED** [review]
This isn't directly related to this PR, but I'm wondering if we should update our Detox emulator to use a device with API level 33 so that it's aligned with this

**Comment by timwright12** [comment]
@theodur that's a good note! I'll take a look at it (probably in another PR)

**Comment by timwright12** [comment]
QA approved on the ticket (cc @DJUltraTom )

**Pull request merged**
