### PR TITLE
feature/9759-Add AppointmentMedicationWording to InPerson Phone & CC

### PR DESCRIPTION
**Pull request by juancstlm-a6**
## Description of Change
Update the content in a In person Appointment and Community Care Appointment details to include the following component when  `Upcoming` and `Cancelled` status. Existing content/wording relating to medication wording will be removed in favor of only the component listed below. 
Image

## Screenshots/Video

<details><summary>iOS</summary>

https://github.com/user-attachments/assets/09e07be1-3bf9-4013-b876-04be1fc4628c

Screenshot 2024-10-09 at 1 45 12 PM

</details>
<details><summary>Android</summary>

https://github.com/user-attachments/assets/1b242945-49fb-4ff7-a058-6a5a7e993d65

Screenshot 2024-10-09 at 1 44 43 PM
</details>

## Testing

- Updated test for In Person, Community Care, and Phone Tests to account for new component showing on  `Upcoming` and `Cancelled` statuses
- [X] Tested on iOS 
- [X] Tested on Android 

## Reviewer Validations
- [ ] Update In person Appointment details to include the "Medication wording" component for `Upcoming` and `Cancelled` status
- [ ] Update Community Care Appointment details to include the "Medication wording" component `Upcoming` and `Cancelled` status
- [ ] Update Phone Appointment details to include the "Medication wording" component `Upcoming` and `Cancelled` status
- [ ]  Update VideoVA Appointment details to include the "Medication wording" component `Upcoming` and `Cancelled` status
- [ ] "Medication wording" component contains a link that opens https://www.va.gov/resources/what-should-i-bring-to-my-health-care-appointments/ in a in app web view
- [ ] ENV file is updated with the appropriate link

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [x] PR is connected to issue(s)
- [X] Tests are included to cover this change (when possible)
- [X] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [X] No secrets or API keys are checked in
- [X] All imports are absolute (no relative imports)
- [X] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

### CODE REVIEW

**Comment by TKDickson** [comment]
@juancstlm-a6 I was taking a look at this ticket for testing assignment, and noticed that the spacing between the content and the link doesn't meet our minimum requirements. You'll need to increase it to match the spacing on the mock in the design library, FYI: https://www.figma.com/design/QVLPB3eOunmKrgQOuOt0SU/Flagship-Library---%F0%9F%93%90-Resource---VA-Mobile?node-id=4598-17424&t=rZu6KwpJc4zhhOzC-4

**Comment by juancstlm-a6** [comment]
> @juancstlm-a6 I was taking a look at this ticket for testing assignment, and noticed that the spacing between the content and the link doesn't meet our minimum requirements. You'll need to increase it to match the spacing on the mock in the design library, FYI: https://www.figma.com/design/QVLPB3eOunmKrgQOuOt0SU/Flagship-Library---%F0%9F%93%90-Resource---VA-Mobile?node-id=4598-17424&t=rZu6KwpJc4zhhOzC-4


Do you mean this spacing ? or the one below the link ? 
Screenshot 2024-10-11 at 3 09 26 PM

**Comment by TKDickson** [comment]
@juancstlm-a6 yep that spacing.

**Comment by juancstlm-a6** [comment]
@TKDickson It seems that it already is the correct spacing. Below is a gif of the simulator overlayed on the figma file while I toggle the opacity on and off. I lined up the headers and the link icon and it seems dead on to me. Would you suggest increasing or decreasing the spacing ? 
Kapture 2024-10-11 at 15 03 07

The spacing that I see incorrect is from the "Details you shared with ..." and the "TTY link" happy to fix that in a separate ticket.

**Comment by TKDickson** [comment]
@juancstlm-a6 yeah your spacing looks good. I was looking at the Figma designs linked in the ticket, which don't have the correct spacing, and assumed that you had built to match those; hadn't brought up the branch.

**Comment by dumathane** [comment]
@alexandec can you PR this for Juan this week?

**Review by alexandec — CHANGES_REQUESTED** [review]
Looks good overall, just a couple test-related things:
- Could you update the E2E tests to check for the new content and link?
- For the unit tests, we have a new best practice of calling the translation function instead of checking for a string. See docs here: https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/Testing/UnitTesting#targeting-by-translated-text

**Comment by juancstlm-a6** [comment]
@alexandec Thanks for the review. I have updated the PR to address your points. 
I added e2e tests to check that the components show in the right places I left this checking against text as trying to tests against the translation function had errors and I didn't see any existing e2e test that do this. 
Updated the unit test to check against the translation function (this is great btw)

**Comment by alexandec** [comment]
@juancstlm-a6 looks good, thanks for making those changes. We haven't tried using the t function in E2E tests yet, no worries there

**Review by alexandec — APPROVED** [review]

**Review by TKDickson — APPROVED** [review]

**Pull request merged**
