### PR TITLE
bug/10117-rachael-detox-fix-onboarding-after-push-notifications

### PR DESCRIPTION
**Pull request by rbontrager**
## Description of Change

Fix the onboarding screen failures caused by the new notifications screen.

Passing android [here](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/11743711234)

## Testing

- [ ] Tested on iOS 
- [ ] Tested on Android 

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [ ] PR is connected to issue(s)
- [ ] Tests are included to cover this change (when possible)
- [ ] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [ ] No secrets or API keys are checked in
- [ ] All imports are absolute (no relative imports)
- [ ] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

### CODE REVIEW

**Review by TKDickson — APPROVED** [review]

**Review by TKDickson — COMMENTED** [review]
nvm, you have a conflict to resolve now

**Review by TKDickson — CHANGES_REQUESTED** [review]
ugh the buttons today, see above

**Comment by TKDickson** [comment]
[iOS](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/11744240704) passing after changes. [Android](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/11744237780) crashed the first time, re-running.

**Review by TKDickson — APPROVED** [review]
Android passed on the re-run, approving.

**Review by dumathane — APPROVED** [review]

**Pull request merged**
