### PR TITLE
bug/7926-PushNotificationsFailedAPICall

### PR DESCRIPTION
**Pull request by theodur**
## Description of Change

Prevents the push notifications preferences endpoint (`/mobile/v0/push/prefs/`) from being called when the endpoint SID is `null`.

## Screenshots/Video

N/A

## Testing

Tested locally on Android emulator with Judy. 

- [ ] Tested on iOS 
- [x] Tested on Android 

## Reviewer Validations

Verify the `/mobile/v0/push/prefs` endpoint isn't being called when the endpoint SID is `null`.

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [ ] PR is connected to issue(s)
- [ ] Tests are included to cover this change (when possible)
- [ ] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [ ] No secrets or API keys are checked in
- [ ] All imports are absolute (no relative imports)
- [ ] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

### CODE REVIEW

**Review by Sparowhawk — DISMISSED** [review]

**Comment by TKDickson** [comment]
two issues on ticket

**Comment by timwright12** [comment]
@theodur does this PR need a nudge?

**Comment by theodur** [comment]
@timwright12 This one previously did, but this morning we actually decided to move these changes to #8254 instead. I'll move this to draft in the meantime

**Comment by theodur** [comment]
Closing this now that I've added these changes to #8254

**Pull request closed without merging**
