### PR TITLE
Automation/6261-Liz-require-qa-approval

### PR DESCRIPTION
**Pull request by liztownd**
## Description of Change
Adding a GitHub workflow to block a merge if QA approval is required and it hasn't been recieved.

## Screenshots/Video
No UI changes.

## Testing
Must test in the pipeline.

- [ ] Tested on iOS 
- [ ] Tested on Android 

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [ ] PR is connected to issue(s)
- [ ] Tests are included to cover this change (when possible)
- [ ] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [ ] No secrets or API keys are checked in
- [ ] All imports are absolute (no relative imports)
- [ ] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

### CODE REVIEW

**Review by Sparowhawk — CHANGES_REQUESTED** [review]

**Comment by liztownd** [comment]
ATTENTION REVIEWERS: THIS IS A TESTING PR ONLY - when it's actually ready for review and merging there will be a new branch and a new PR.

**Review by TKDickson — APPROVED** [review]

**Comment by TKDickson** [comment]
Fake-approving right now to help test the logic

**Review by TKDickson — APPROVED** [review]

**Review by hasahmed2 — APPROVED** [review]

**Review by TKDickson — DISMISSED** [review]

**Review by dumathane — APPROVED** [review]

**Review by hasahmed2 — DISMISSED** [review]

**Review by TKDickson — DISMISSED** [review]

**Review by hasahmed2 — APPROVED** [review]

**Review by Sparowhawk — APPROVED** [review]

**Review by TKDickson — APPROVED** [review]

**Review by TKDickson — APPROVED** [review]

**Review by hasahmed2 — DISMISSED** [review]

**Review by hasahmed2 — DISMISSED** [review]

**Review by TKDickson — DISMISSED** [review]

**Review by hasahmed2 — APPROVED** [review]

**Review by TKDickson — APPROVED** [review]

**Review by hasahmed2 — APPROVED** [review]

**Review by TKDickson — DISMISSED** [review]

**Review by timwright12 — DISMISSED** [review]
fake approval for testing!

**Review by hasahmed2 — APPROVED** [review]

**Review by hasahmed2 — APPROVED** [review]

**Review by timwright12 — DISMISSED** [review]

**Review by dumathane — APPROVED** [review]

**Review by dumathane — APPROVED** [review]

**Review by timwright12 — DISMISSED** [review]

**Review by hasahmed2 — APPROVED** [review]

**Review by TKDickson — DISMISSED** [review]

**Review by timwright12 — DISMISSED** [review]

**Review by Sparowhawk — APPROVED** [review]

**Review by dumathane — APPROVED** [review]

**Review by dumathane — APPROVED** [review]

**Review by Sparowhawk — APPROVED** [review]

**Review by timwright12 — APPROVED** [review]

**Comment by timwright12** [comment]
Moved this code to: https://github.com/department-of-veterans-affairs/va-mobile-app/pull/7562

**Pull request closed without merging**
